import jsPDF from "jspdf";
import "jspdf-autotable";
 
// ─── Colour & Typography constants ───────────────────────────────────────────
const BRAND = {
  primary: [34, 211, 238],   // cyan-400  #22D3EE
  dark:    [15,  23,  42],   // slate-900 #0F172A
  heading: [14, 165, 233],   // sky-500   #0EA5E9
  body:    [30,  41,  59],   // slate-800 #1E293B
  muted:   [100, 116, 139],  // slate-500 #64748B
  white:   [255, 255, 255],
  light:   [241, 245, 249],  // slate-100
  border:  [203, 213, 225],  // slate-300
};
 
const FONT = {
  title:    { size: 22, style: "bold" },
  h1:       { size: 18, style: "bold" },
  h2:       { size: 15, style: "bold" },
  h3:       { size: 13, style: "bold" },
  body:     { size: 11, style: "normal" },
  code:     { size: 9,  style: "normal" },
  small:    { size: 9,  style: "normal" },
  footer:   { size: 8,  style: "normal" },
};
 
const PAGE = {
  width: 210,   // A4 mm
  height: 297,
  marginX: 18,
  marginTop: 28,
  marginBottom: 20,
  lineHeight: 6,
};
 
// ─── Main export ─────────────────────────────────────────────────────────────
 
/**
 * @param {string} markdown   - The raw Markdown string from AI
 * @param {object} options
 *   @param {string} options.title          - Document title shown in header
 *   @param {string} options.filename       - Output filename (no .pdf needed)
 *   @param {string} [options.watermarkText]  - Diagonal watermark (e.g. "LESSONLY")
 *   @param {string} [options.headerText]     - Top-right corner brand text
 *   @param {string} [options.headerImageUrl] - URL/path to logo image (optional)
 */
export async function generatePDFFromMarkdown(markdown, options = {}) {
  const {
    title = "Document",
    filename = "document",
    watermarkText = "LESSONLY",
    headerText = "LESSONLY",
    headerImageUrl = null,
  } = options;
 
  const doc = new jsPDF({ unit: "mm", format: "a4", putOnlyUsedFonts: true });
  const usableWidth = PAGE.width - PAGE.marginX * 2;
  let y = PAGE.marginTop;
 
  // ── Helper: add header/footer to every page ──────────────────────────────
  const addPageDecorations = async (pageNum, totalPages, logoDataUrl) => {
    // Header bar
    doc.setFillColor(...BRAND.dark);
    doc.rect(0, 0, PAGE.width, 14, "F");
 
    // Logo (if available)
    if (logoDataUrl) {
      try {
        doc.addImage(logoDataUrl, "PNG", PAGE.marginX, 2, 10, 10);
      } catch (_) { /* skip if image fails */ }
    }
 
    // Brand text top-right
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...BRAND.primary);
    doc.text(headerText, PAGE.width - PAGE.marginX, 9, { align: "right" });
 
    // Footer
    doc.setFillColor(...BRAND.light);
    doc.rect(0, PAGE.height - PAGE.marginBottom + 4, PAGE.width, PAGE.marginBottom, "F");
    doc.setDrawColor(...BRAND.border);
    doc.setLineWidth(0.3);
    doc.line(PAGE.marginX, PAGE.height - PAGE.marginBottom + 4, PAGE.width - PAGE.marginX, PAGE.height - PAGE.marginBottom + 4);
 
    doc.setFont("helvetica", "normal");
    doc.setFontSize(FONT.footer.size);
    doc.setTextColor(...BRAND.muted);
    doc.text(
      `Generated by ${headerText} · ${new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" })}`,
      PAGE.marginX,
      PAGE.height - 6
    );
    doc.text(`Page ${pageNum} of ${totalPages}`, PAGE.width - PAGE.marginX, PAGE.height - 6, { align: "right" });
 
    // Diagonal watermark
    if (watermarkText) {
      doc.saveGraphicsState();
      doc.setGState(new doc.GState({ opacity: 0.04 }));
      doc.setFont("helvetica", "bold");
      doc.setFontSize(55);
      doc.setTextColor(...BRAND.dark);
      doc.text(watermarkText, PAGE.width / 2, PAGE.height / 2, {
        align: "center",
        angle: 45,
        baseline: "middle",
      });
      doc.restoreGraphicsState();
    }
  };
 
  // ── Helper: ensure enough vertical space, add page if needed ─────────────
  const checkY = (needed = 10) => {
    if (y + needed > PAGE.height - PAGE.marginBottom - 4) {
      doc.addPage();
      y = PAGE.marginTop;
    }
  };
 
  // ── Helper: wrapped text block ────────────────────────────────────────────
  const writeText = (text, { size, style, color, indent = 0, spacing = 1.5 } = {}) => {
    doc.setFont("helvetica", style || "normal");
    doc.setFontSize(size || FONT.body.size);
    doc.setTextColor(...(color || BRAND.body));
 
    const lines = doc.splitTextToSize(text, usableWidth - indent);
    const blockH = lines.length * (size || FONT.body.size) * 0.352778 * spacing + 2;
    checkY(blockH);
    doc.text(lines, PAGE.marginX + indent, y);
    y += blockH;
  };
 
  // ── Helper: horizontal divider ────────────────────────────────────────────
  const writeDivider = (color = BRAND.border) => {
    checkY(4);
    doc.setDrawColor(...color);
    doc.setLineWidth(0.3);
    doc.line(PAGE.marginX, y, PAGE.width - PAGE.marginX, y);
    y += 4;
  };
 
  // ── Helper: bullet item ───────────────────────────────────────────────────
  const writeBullet = (text, level = 0) => {
    const indent = 4 + level * 5;
    const bullet = level === 0 ? "•" : level === 1 ? "◦" : "▸";
    doc.setFont("helvetica", "normal");
    doc.setFontSize(FONT.body.size);
    doc.setTextColor(...BRAND.body);
 
    const lines = doc.splitTextToSize(text, usableWidth - indent - 6);
    const blockH = lines.length * FONT.body.size * 0.352778 * 1.5 + 1;
    checkY(blockH);
 
    doc.text(bullet, PAGE.marginX + indent, y);
    doc.text(lines, PAGE.marginX + indent + 5, y);
    y += blockH;
  };
 
  // ── Helper: numbered item ─────────────────────────────────────────────────
  const writeNumbered = (text, num) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(FONT.body.size);
    doc.setTextColor(...BRAND.body);
 
    const prefix = `${num}.  `;
    const lines = doc.splitTextToSize(text, usableWidth - 10);
    const blockH = lines.length * FONT.body.size * 0.352778 * 1.5 + 1;
    checkY(blockH);
 
    doc.setFont("helvetica", "bold");
    doc.text(`${num}.`, PAGE.marginX + 2, y);
    doc.setFont("helvetica", "normal");
    doc.text(lines, PAGE.marginX + 10, y);
    y += blockH;
  };
 
  // ── Helper: inline code block ─────────────────────────────────────────────
  const writeCodeBlock = (code) => {
    const lines = code.split("\n");
    const blockH = lines.length * FONT.code.size * 0.352778 * 1.6 + 8;
    checkY(blockH);
 
    // Background
    doc.setFillColor(15, 23, 42); // slate-900
    doc.roundedRect(PAGE.marginX, y - 2, usableWidth, blockH - 2, 2, 2, "F");
    doc.setDrawColor(...BRAND.border);
    doc.setLineWidth(0.2);
    doc.roundedRect(PAGE.marginX, y - 2, usableWidth, blockH - 2, 2, 2, "S");
 
    doc.setFont("courier", "normal");
    doc.setFontSize(FONT.code.size);
    doc.setTextColor(134, 239, 172); // green-300
 
    lines.forEach((line) => {
      const wrapped = doc.splitTextToSize(line || " ", usableWidth - 8);
      doc.text(wrapped, PAGE.marginX + 4, y + 2);
      y += wrapped.length * FONT.code.size * 0.352778 * 1.6;
    });
    y += 6;
  };
 
  // ── Helper: blockquote ────────────────────────────────────────────────────
  const writeBlockquote = (text) => {
    const lines = doc.splitTextToSize(text, usableWidth - 12);
    const blockH = lines.length * FONT.body.size * 0.352778 * 1.5 + 6;
    checkY(blockH);
 
    doc.setFillColor(226, 232, 240); // slate-200
    doc.rect(PAGE.marginX, y - 2, 2, blockH, "F");
    doc.setFillColor(241, 245, 249);
    doc.rect(PAGE.marginX + 2, y - 2, usableWidth - 2, blockH, "F");
 
    doc.setFont("helvetica", "italic");
    doc.setFontSize(FONT.body.size);
    doc.setTextColor(...BRAND.muted);
    doc.text(lines, PAGE.marginX + 6, y + 2);
    y += blockH + 2;
  };
 
  // ── Heading with background accent ───────────────────────────────────────
  const writeHeading = (text, level) => {
    const cfg = level === 1 ? FONT.h1 : level === 2 ? FONT.h2 : FONT.h3;
    const h = cfg.size * 0.352778 * 1.8 + 4;
    checkY(h + 4);
 
    if (level === 1) {
      doc.setFillColor(...BRAND.dark);
      doc.rect(PAGE.marginX, y - 3, usableWidth, h, "F");
      // Cyan accent bar
      doc.setFillColor(...BRAND.primary);
      doc.rect(PAGE.marginX, y - 3, 3, h, "F");
 
      doc.setFont("helvetica", "bold");
      doc.setFontSize(cfg.size);
      doc.setTextColor(...BRAND.white);
      doc.text(text, PAGE.marginX + 7, y + h / 2 - 2);
      y += h + 4;
    } else if (level === 2) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(cfg.size);
      doc.setTextColor(...BRAND.heading);
      doc.text(text, PAGE.marginX, y + cfg.size * 0.352778);
      y += cfg.size * 0.352778 * 1.6 + 2;
      // Underline
      doc.setDrawColor(...BRAND.primary);
      doc.setLineWidth(0.5);
      doc.line(PAGE.marginX, y, PAGE.marginX + 50, y);
      y += 3;
    } else {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(cfg.size);
      doc.setTextColor(...BRAND.body);
      doc.text(text, PAGE.marginX, y + cfg.size * 0.352778);
      y += cfg.size * 0.352778 * 1.6 + 2;
    }
  };
 
  // ── Helper: render Markdown table with autoTable ─────────────────────────
  const writeTable = (rows) => {
    if (rows.length < 2) return;
    const headers = rows[0].map((h) => h.trim().replace(/\*\*/g, ""));
    const body = rows.slice(2).map((r) => r.map((c) => c.trim().replace(/\*\*/g, "")));
 
    checkY(20);
    doc.autoTable({
      startY: y,
      head: [headers],
      body,
      margin: { left: PAGE.marginX, right: PAGE.marginX },
      styles: {
        font: "helvetica",
        fontSize: 9,
        cellPadding: 3,
        textColor: BRAND.body,
        lineColor: BRAND.border,
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: BRAND.dark,
        textColor: BRAND.white,
        fontStyle: "bold",
        halign: "left",
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      theme: "grid",
    });
    y = doc.lastAutoTable.finalY + 6;
  };
 
  // ── Title page ────────────────────────────────────────────────────────────
  const drawTitlePage = async (logoDataUrl) => {
    // Full dark background
    doc.setFillColor(...BRAND.dark);
    doc.rect(0, 0, PAGE.width, PAGE.height, "F");
 
    // Decorative top band
    doc.setFillColor(...BRAND.primary);
    doc.rect(0, 0, PAGE.width, 3, "F");
 
    // Logo
    if (logoDataUrl) {
      try {
        doc.addImage(logoDataUrl, "PNG", PAGE.width / 2 - 15, 40, 30, 30);
      } catch (_) {}
    }
 
    // Brand
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...BRAND.primary);
    doc.text(headerText, PAGE.width / 2, 80, { align: "center" });
 
    // Title
    const titleLines = doc.splitTextToSize(title, PAGE.width - 50);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(26);
    doc.setTextColor(...BRAND.white);
    titleLines.forEach((line, i) => {
      doc.text(line, PAGE.width / 2, 100 + i * 12, { align: "center" });
    });
 
    // Divider
    doc.setDrawColor(...BRAND.primary);
    doc.setLineWidth(0.8);
    const tw = Math.min(doc.getTextWidth(title) + 20, PAGE.width - 50);
    doc.line(PAGE.width / 2 - tw / 2, 115 + titleLines.length * 12 - 12, PAGE.width / 2 + tw / 2, 115 + titleLines.length * 12 - 12);
 
    // Date
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...BRAND.muted);
    doc.text(
      new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" }),
      PAGE.width / 2,
      130 + titleLines.length * 12,
      { align: "center" }
    );
 
    // Bottom decoration
    doc.setFillColor(...BRAND.primary);
    doc.rect(0, PAGE.height - 3, PAGE.width, 3, "F");
  };
 
  // ─── Main parsing logic ───────────────────────────────────────────────────
 
  // Load logo as data URL for embedding
  let logoDataUrl = null;
  if (headerImageUrl) {
    try {
      logoDataUrl = await loadImageAsDataURL(headerImageUrl);
    } catch (_) {}
  }
 
  // Title page
  await drawTitlePage(logoDataUrl);
 
  // Content starts on page 2
  doc.addPage();
  y = PAGE.marginTop;
 
  // Parse Markdown line by line
  const lines = markdown.split("\n");
  let i = 0;
  let orderedCounter = 0;
 
  while (i < lines.length) {
    const line = lines[i];
 
    // ── Fenced code block ````
    if (line.trimStart().startsWith("```")) {
      const codeLines = [];
      i++;
      while (i < lines.length && !lines[i].trimStart().startsWith("```")) {
        codeLines.push(lines[i]);
        i++;
      }
      writeCodeBlock(codeLines.join("\n"));
      i++;
      continue;
    }
 
    // ── Headings
    if (/^#{1,3}\s/.test(line)) {
      const level = line.match(/^(#+)/)[1].length;
      const text = line.replace(/^#+\s*/, "").replace(/\*\*/g, "").trim();
      writeHeading(text, Math.min(level, 3));
      orderedCounter = 0;
      i++;
      continue;
    }
 
    // ── Horizontal rule
    if (/^[-*_]{3,}$/.test(line.trim())) {
      writeDivider(BRAND.primary);
      i++;
      continue;
    }
 
    // ── Blockquote
    if (line.startsWith(">")) {
      const text = line.replace(/^>\s*/, "").trim();
      writeBlockquote(text);
      i++;
      continue;
    }
 
    // ── Table detection (row starts with |)
    if (line.trim().startsWith("|")) {
      const tableRows = [];
      while (i < lines.length && lines[i].trim().startsWith("|")) {
        const cells = lines[i].split("|").filter((c) => c.trim() !== "").map((c) => c.trim());
        tableRows.push(cells);
        i++;
      }
      writeTable(tableRows);
      continue;
    }
 
    // ── Unordered bullet
    if (/^(\s*)[-*+]\s/.test(line)) {
      const indent = line.match(/^(\s*)/)[1].length;
      const level = Math.floor(indent / 2);
      const text = line.replace(/^(\s*)[-*+]\s/, "").replace(/\*\*(.*?)\*\*/g, "$1").trim();
      writeBullet(text, level);
      orderedCounter = 0;
      i++;
      continue;
    }
 
    // ── Ordered list
    if (/^\d+\.\s/.test(line.trim())) {
      orderedCounter++;
      const text = line.replace(/^\d+\.\s/, "").replace(/\*\*(.*?)\*\*/g, "$1").trim();
      writeNumbered(text, orderedCounter);
      i++;
      continue;
    }
 
    // ── Empty line → spacing
    if (line.trim() === "") {
      y += 3;
      orderedCounter = 0;
      i++;
      continue;
    }
 
    // ── Regular paragraph
    const cleaned = line
      .replace(/\*\*(.*?)\*\*/g, "$1")   // remove bold markers
      .replace(/\*(.*?)\*/g, "$1")        // remove italic markers
      .replace(/`(.*?)`/g, "$1")          // remove inline code backticks
      .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1") // remove links, keep text
      .trim();
 
    if (cleaned) {
      writeText(cleaned, { size: FONT.body.size, color: BRAND.body });
    }
 
    orderedCounter = 0;
    i++;
  }
 
  // ── Add header/footer decorations to all pages ───────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    if (p > 1) {
      // Only content pages (page 1 is title page, skip decorations)
      await addPageDecorations(p - 1, totalPages - 1, logoDataUrl);
    }
  }
 
  // ── Save ─────────────────────────────────────────────────────────────────
  const safeFilename = filename.replace(/\.pdf$/i, "").replace(/[^a-z0-9\-_ ]/gi, "_");
  doc.save(`${safeFilename}.pdf`);
}
 
// ─── Utility: load image as base64 dataURL ────────────────────────────────
function loadImageAsDataURL(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      canvas.getContext("2d").drawImage(img, 0, 0);
      resolve(canvas.toDataURL("image/png"));
    };
    img.onerror = reject;
    img.src = src;
  });
}